import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeState } from "@style/ThemeState";
import SideBar from "@component/global/SideBar";
import UsersState from "@context/users-context/UsersState";
import NavBar from "@component/global/NavBar";
import MainBox from "@component/global/MainBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const ThemeStateAsync = () => ThemeState
export const UsersStateAsync = () => UsersState


export default function RootLayout({ children }) {
  const ThemeAwait = ThemeStateAsync()
  const UsersAwait = UsersStateAsync()

  return (
    <html lang="en">
      <ThemeAwait >
        <UsersAwait>
          <body className={inter.className}>
            <div className="app">
              <SideBar />
              <div className="content">
                <NavBar />
                <div className="main">
                  <MainBox >
                    {children}
                  </MainBox>
                </div>
              </div>
            </div>
          </body>
        </UsersAwait>
      </ThemeAwait>
    </html>
  );
}
